### ISSUE TITLE
Segmentation Fault with `yppasswd`

### ISSUE THREAD

**Issue by prcastro** [thkukuk/yp-tools#1]
When trying to change a password from on of the machines (not the server) using `yppasswd`, the program crashes with a Segmentation Fault.

```
pcastro@workstation:~$ yppasswd
Changing NIS account information for pcastro on proccm2.
Please enter old password:
Changing NIS password for pcastro on proccm2.
Please enter new password:
Segmentation fault (core dumped)
```

I traced the program with GDB:

```
pcastro@workstation:~$ gdb yppasswd
GNU gdb (GDB) 7.9.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from yppasswd...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/yppasswd 
Changing NIS account information for pcastro on proccm2.
Please enter old password:
Changing NIS password for pcastro on proccm2.
Please enter new password:

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7712980 in __strncmp_ssse3 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7712980 in __strncmp_ssse3 () from /usr/lib/libc.so.6
#1  0x0000000000402754 in ?? ()
#2  0x00007ffff7609790 in __libc_start_main () from /usr/lib/libc.so.6
#3  0x0000000000402ae9 in ?? ()
(gdb) quit
```

On Ubuntu's Launchpad, someone posted a [patch](https://bugs.launchpad.net/ubuntu/+source/nis/+bug/1204530/comments/13) that seems to work.

**Comment by thkukuk** [comment]
Should be fixed in 4.0
